// Stage K item 4: resolve the 6 unmatched AFI Top 100 titles and
// generate the backfill migration.
//
// Stage G's strict (short-title, exact-year) match missed these 6.
// Recon (search_titles RPC) showed all 6 ARE in the catalog — 3 were
// title-variation misses (Dr. Strangelove / Intolerance / Sunrise
// carry fuller TMDb titles), 3 were year-off-by-one (Casablanca,
// Snow White, The African Queen — premiere vs wide-release).
//
// Match per gap: search_titles(fullTitle, 8) -> candidates with an
// exact (case-insensitive) full-title match AND year within ±1 of
// the AFI year; one batched PK fetch for popularity/poster; highest
// popularity wins. Prints every pick for review, then writes
// supabase/migrations/20260514000007_afi_gaps_backfill.sql.
//
// Run: node scripts/_one_shot_resolve_afi_gaps.mjs

import { writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  { auth: { persistSession: false } },
);

const MIGRATION_PATH =
  "supabase/migrations/20260514000007_afi_gaps_backfill.sql";

// [AFI position, full TMDb title, AFI year, year tolerance]
const GAPS = [
  [3, "Casablanca", 1942, 1],
  [34, "Snow White and the Seven Dwarfs", 1937, 1],
  [
    39,
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    1964,
    1,
  ],
  [49, "Intolerance: Love's Struggle Throughout the Ages", 1916, 1],
  [65, "The African Queen", 1951, 1],
  [82, "Sunrise: A Song of Two Humans", 1927, 1],
];

function yearsOf(row) {
  const ys = new Set();
  if (row.year != null) ys.add(Number(row.year));
  for (const d of [row.release_date, row.first_air_date]) {
    if (d) ys.add(Number(String(d).slice(0, 4)));
  }
  return ys;
}

const resolved = [];
const failed = [];

for (const [position, fullTitle, afiYear, tol] of GAPS) {
  const { data, error } = await sb.rpc("search_titles", {
    query: fullTitle,
    max_results: 8,
  });
  if (error) {
    failed.push(`${fullTitle} — RPC error: ${error.message}`);
    continue;
  }
  const lc = fullTitle.toLowerCase();
  const candidateIds = (data ?? [])
    .filter((r) => (r.title ?? "").toLowerCase() === lc)
    .map((r) => r.id);
  if (candidateIds.length === 0) {
    failed.push(`${fullTitle} (${afiYear}) — no exact title match`);
    continue;
  }

  const { data: rows } = await sb
    .from("titles")
    .select("id, title, year, release_date, first_air_date, popularity, poster_url")
    .in("id", candidateIds);

  const yearHits = (rows ?? []).filter((r) =>
    [...yearsOf(r)].some((y) => Math.abs(y - afiYear) <= tol),
  );
  if (yearHits.length === 0) {
    failed.push(
      `${fullTitle} (${afiYear} ±${tol}) — title matched but no year within tolerance`,
    );
    continue;
  }
  yearHits.sort((a, b) => (b.popularity ?? 0) - (a.popularity ?? 0));
  const pick = yearHits[0];
  resolved.push({ position, fullTitle, afiYear, pick });
  console.log(
    `#${position} ${fullTitle} (AFI ${afiYear})\n  -> ${pick.title} | year ${pick.year} | pop ${pick.popularity} | poster ${pick.poster_url ? "yes" : "NO"} | id ${pick.id}`,
  );
}

if (failed.length > 0) {
  console.error(`\n${failed.length} UNRESOLVED — flag back, do not ship:`);
  for (const f of failed) console.error(`  - ${f}`);
  process.exit(1);
}

const values = resolved
  .map((r) => `  ('${r.pick.id}', ${r.position})`)
  .join(",\n");

const sql = `-- Stage K item 4: backfill the 6 AFI Top 100 titles that Stage G's
-- strict matcher missed.
--
-- GENERATED by scripts/_one_shot_resolve_afi_gaps.mjs. Stage G missed
-- these on title variation (Dr. Strangelove / Intolerance / Sunrise
-- carry fuller TMDb titles) and year-off-by-one (Casablanca,
-- Snow White, The African Queen — premiere vs wide-release year).
-- All 6 were found in the existing catalog via search_titles on the
-- full TMDb title with a ±1-year tolerance; no TMDb fetch needed.
-- After this migration the AFI Top 100 list has all 100 positions
-- filled.

insert into public.curated_list_titles (curated_list_id, title_id, position)
select cl.id, v.title_id::uuid, v.position
from (values
${values}
) as v(title_id, position)
cross join public.curated_lists cl
where cl.slug = 'afi-top-100'
on conflict do nothing;
`;

writeFileSync(MIGRATION_PATH, sql);
console.log(`\nResolved ${resolved.length}/6. Wrote ${MIGRATION_PATH}`);
