// Stage G seed builder. Matches the AFI Top 100 + Greatest TV Shows
// seed lists against the production catalog (via the trigram-indexed
// search_titles RPC — a raw .ilike()/.in() on title seq-scans 1.4M
// rows and times out), then GENERATES the static seed migration
// supabase/migrations/20260514000005_seed_curated_lists.sql.
//
// Matching: search_titles(title, 12) -> title-exact candidates;
// one batched .in("id", ...) fetch for year/date/popularity (id is
// the PK, fast); match on (title-exact AND year), prefer highest
// popularity. position = the title's rank in the seed list, so
// unmatched entries leave a gap (e.g. Casablanca #3 missing -> the
// list still ranks the matched titles 1,2,4,5,...). Re-running this
// script regenerates the migration deterministically.
//
// Run: node scripts/_one_shot_match_curated_titles.mjs

import { writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { AFI_TOP_100, GREATEST_TV_SHOWS } from "./_curated_seed_data.mjs";

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  { auth: { persistSession: false } },
);

const MIGRATION_PATH =
  "supabase/migrations/20260514000005_seed_curated_lists.sql";

function yearsOf(row) {
  const ys = new Set();
  if (row.year != null) ys.add(Number(row.year));
  for (const d of [row.release_date, row.first_air_date]) {
    if (d) ys.add(Number(String(d).slice(0, 4)));
  }
  return ys;
}

async function matchList(label, list) {
  const candidateIds = new Set();
  const perSeed = [];
  for (const [title, year] of list) {
    const { data, error } = await sb.rpc("search_titles", {
      query: title,
      max_results: 12,
    });
    if (error) {
      perSeed.push({ title, year, ids: [] });
      continue;
    }
    const lc = title.toLowerCase();
    const ids = (data ?? [])
      .filter((r) => (r.title ?? "").toLowerCase() === lc)
      .map((r) => r.id);
    ids.forEach((id) => candidateIds.add(id));
    perSeed.push({ title, year, ids });
  }

  const byId = new Map();
  const idArr = [...candidateIds];
  for (let i = 0; i < idArr.length; i += 200) {
    const { data } = await sb
      .from("titles")
      .select("id, title, year, release_date, first_air_date, popularity")
      .in("id", idArr.slice(i, i + 200));
    for (const r of data ?? []) byId.set(r.id, r);
  }

  const matched = []; // { title_id, position }
  const missing = [];
  list.forEach(([title, year], idx) => {
    const position = idx + 1; // rank in the seed list
    const seed = perSeed.find((s) => s.title === title && s.year === year);
    const rows = (seed?.ids ?? [])
      .map((id) => byId.get(id))
      .filter(Boolean)
      .filter((r) => yearsOf(r).has(year));
    if (rows.length === 0) {
      missing.push(`${title} (${year})`);
      return;
    }
    rows.sort((a, b) => (b.popularity ?? 0) - (a.popularity ?? 0));
    matched.push({ title_id: rows[0].id, position });
  });

  console.log(`\n=== ${label} ===`);
  console.log(`matched: ${matched.length}/${list.length}`);
  if (missing.length) {
    console.log(`missing (${missing.length}):`);
    for (const m of missing) console.log(`  - ${m}`);
  }
  return { matched, missing };
}

const afi = await matchList("AFI Top 100", AFI_TOP_100);
const tv = await matchList("Greatest TV Shows", GREATEST_TV_SHOWS);

function titlesBlock(slug, rows) {
  if (rows.length === 0) return "";
  const values = rows
    .map((r) => `  ('${r.title_id}', ${r.position})`)
    .join(",\n");
  return `
insert into public.curated_list_titles (curated_list_id, title_id, position)
select cl.id, v.title_id::uuid, v.position
from (values
${values}
) as v(title_id, position)
cross join public.curated_lists cl
where cl.slug = '${slug}'
on conflict do nothing;
`;
}

const sql = `-- Stage G: seed the AFI Top 100 and Greatest TV Shows curated lists.
--
-- GENERATED by scripts/_one_shot_match_curated_titles.mjs — re-run
-- that script to regenerate. The curated_lists rows are static; the
-- curated_list_titles rows carry title_ids resolved by matching the
-- seed lists against the catalog (search_titles RPC, exact title +
-- year, highest popularity wins).
--
-- position = the title's rank in the source list. Unmatched entries
-- (catalog title-variation misses — e.g. "Dr. Strangelove" vs the
-- full TMDb title) leave a position gap and are banked for manual
-- curation. As of generation:
--   AFI Top 100:        ${afi.matched.length}/${AFI_TOP_100.length} matched
--   Greatest TV Shows:  ${tv.matched.length}/${GREATEST_TV_SHOWS.length} matched

insert into public.curated_lists (slug, name, description, display_order, is_visible)
values
  ('afi-top-100', 'AFI Top 100', null, 30, true),
  ('greatest-tv-shows', 'Greatest TV Shows of All Time', null, 40, true)
on conflict (slug) do nothing;
${titlesBlock("afi-top-100", afi.matched)}${titlesBlock("greatest-tv-shows", tv.matched)}`;

writeFileSync(MIGRATION_PATH, sql);
console.log(`\nWrote ${MIGRATION_PATH}`);
console.log(
  `Total: ${afi.matched.length + tv.matched.length}/${
    AFI_TOP_100.length + GREATEST_TV_SHOWS.length
  } matched`,
);
