-- Stage K item 4: backfill the 6 AFI Top 100 titles that Stage G's
-- strict matcher missed.
--
-- GENERATED by scripts/_one_shot_resolve_afi_gaps.mjs. Stage G missed
-- these on title variation (Dr. Strangelove / Intolerance / Sunrise
-- carry fuller TMDb titles) and year-off-by-one (Casablanca,
-- Snow White, The African Queen — premiere vs wide-release year).
-- All 6 were found in the existing catalog via search_titles on the
-- full TMDb title with a ±1-year tolerance; no TMDb fetch needed.
-- After this migration the AFI Top 100 list has all 100 positions
-- filled.

insert into public.curated_list_titles (curated_list_id, title_id, position)
select cl.id, v.title_id::uuid, v.position
from (values
  ('32f062d4-6a26-4144-b96d-43cf9be51999', 3),
  ('856e30d5-4631-4e7f-8f51-e05a70016d11', 34),
  ('2cc57666-f028-46ce-9023-266fe80c9107', 39),
  ('6d66e3a4-11cf-4a80-a1ee-f88abfaca152', 49),
  ('fa7e420a-721d-4adb-94eb-51e4598ba41a', 65),
  ('4d21c0de-ed29-40f6-833b-e42245eba4b9', 82)
) as v(title_id, position)
cross join public.curated_lists cl
where cl.slug = 'afi-top-100'
on conflict do nothing;
