-- Stage G: seed the AFI Top 100 and Greatest TV Shows curated lists.
--
-- GENERATED by scripts/_one_shot_match_curated_titles.mjs — re-run
-- that script to regenerate. The curated_lists rows are static; the
-- curated_list_titles rows carry title_ids resolved by matching the
-- seed lists against the catalog (search_titles RPC, exact title +
-- year, highest popularity wins).
--
-- position = the title's rank in the source list. Unmatched entries
-- (catalog title-variation misses — e.g. "Dr. Strangelove" vs the
-- full TMDb title) leave a position gap and are banked for manual
-- curation. As of generation:
--   AFI Top 100:        94/100 matched
--   Greatest TV Shows:  50/50 matched

insert into public.curated_lists (slug, name, description, display_order, is_visible)
values
  ('afi-top-100', 'AFI Top 100', null, 30, true),
  ('greatest-tv-shows', 'Greatest TV Shows of All Time', null, 40, true)
on conflict (slug) do nothing;

insert into public.curated_list_titles (curated_list_id, title_id, position)
select cl.id, v.title_id::uuid, v.position
from (values
  ('d62e505f-b061-4412-83ab-bb66a6504eee', 1),
  ('5e435c4c-f216-4a59-8b87-4ed4f60cbdf9', 2),
  ('46255284-6cf0-49ee-ba16-5bbb5eba7df1', 4),
  ('caec3f60-daca-473f-acf6-9fe6936239b5', 5),
  ('b5cf30f7-d761-4267-84ce-31b8ebbdf4d6', 6),
  ('d522f879-c5d6-4d38-99fd-ff98f03568af', 7),
  ('4bf8699a-5c29-4cd0-9205-93961ea6a0b2', 8),
  ('2197b613-6d08-4383-8018-e2ccf7cb1c43', 9),
  ('150e6d55-91a5-4b82-924d-b06558d2b275', 10),
  ('d8a4634b-b8d5-414d-886c-249cb6b87b81', 11),
  ('1dc23641-eee9-4bd1-b718-184981115af9', 12),
  ('b05bb26f-c226-4ac9-ac45-0917ed834765', 13),
  ('ee25a057-df83-4fbf-9290-f842afe8617c', 14),
  ('ce265111-f13a-4ba5-a1f3-867277566db2', 15),
  ('09e8a723-8e5b-44e0-918a-f0ab68cd124f', 16),
  ('205bd64a-2c6f-4c0a-a0d3-157516ae17f3', 17),
  ('9cf57a01-0a3c-451b-bfdd-92135098ff38', 18),
  ('ae106bc2-6659-4d05-b7ea-8908087018fe', 19),
  ('856979d1-084c-41f9-b4df-04c4f6445259', 20),
  ('6a6e38af-dc3c-4afa-8a43-b6341111cd5f', 21),
  ('c17492f0-2e35-4c53-87f8-9898de77f7d4', 22),
  ('0a491e90-255a-42c1-8461-75b2abec97da', 23),
  ('02a2d9ab-8fa0-4c97-b450-f4bcf6dd9dad', 24),
  ('f8bc5ca3-de3f-4c7c-91c3-ff1eafc73888', 25),
  ('2f806d8c-edc5-495c-8669-6137cfd6d965', 26),
  ('7ba5f53f-a1c5-4022-80ba-69d0b5208bbd', 27),
  ('0bf95613-931f-4b26-94bf-de2ba6b9f8b6', 28),
  ('9ab60596-8e16-450e-be70-28e1fe4e00f6', 29),
  ('fcfb91cd-7eeb-4108-8b3d-b166d386dc0a', 30),
  ('3b615d05-3b27-46d3-a1d1-3ad4c4eb7581', 31),
  ('5da16e26-05a6-485c-8006-3302cf4ad001', 32),
  ('1cabd12c-1f55-4f56-9bea-8834b0484695', 33),
  ('91870991-17e3-419e-8a17-fdd6b9814381', 35),
  ('0d4050b7-d644-4552-8ddb-279e1cd2d8f7', 36),
  ('f01d9e2f-9cd2-43bd-a271-47fb12172133', 37),
  ('0817e264-333a-4334-b9ac-2358a7b1b0e9', 38),
  ('cd8733a6-4c6b-4765-b7c4-61d9ea5eed0d', 40),
  ('8a545c99-dc96-4613-b96c-85b18c54d4f3', 41),
  ('0040f7da-093c-4d2d-a7e9-6ac09f642483', 42),
  ('62824c7b-397f-4116-81bf-c77ae758294d', 43),
  ('03416954-fbf4-4966-ba22-52ca72c717f6', 44),
  ('0f491eea-ac53-4765-b824-b0763ecafed2', 45),
  ('1b47331d-0854-4cfb-9eb0-7c838442eed4', 46),
  ('807a9dfc-776a-4994-8c73-79b49fb22612', 47),
  ('04f80f19-b9a5-4141-bcf2-ef9098fe30bc', 48),
  ('fc1723c6-45db-4a56-b7bf-2ca26877876f', 50),
  ('241c7019-43e8-4edc-a7e8-2b2ccd64b931', 51),
  ('31589e28-7261-4ed7-a0ac-d0b7242a3db6', 52),
  ('d8fcbea9-a96e-42df-9fdf-c71df8a471b2', 53),
  ('232291b2-b595-446c-b206-127a9d274f34', 54),
  ('b2052060-092f-4a43-8994-1e3baa4610ee', 55),
  ('68a26ded-4968-4e63-8695-10fd57cb1e9b', 56),
  ('bf6eb463-5a87-4e3f-92ad-caa8167aff7d', 57),
  ('2761cece-d5c5-4e89-b205-982b06c5acf0', 58),
  ('fe90ca1f-4899-40d7-b446-2e151ffc4a1d', 59),
  ('cba43c58-3df4-4126-b94d-02316e7c9689', 60),
  ('d33d8dd3-0f52-41cf-b7f8-240f1bb2f5f9', 61),
  ('0ee2c7ef-a104-43f1-abdc-888744e0e6e9', 62),
  ('be8bfade-12c2-46a5-8b29-098795c0043d', 63),
  ('44a180c2-e38d-43b0-9bfe-f21d01fa1a68', 64),
  ('afced548-ca81-414c-a10a-fa06e2fc34cf', 66),
  ('3cf681a0-4d8d-41b0-a06d-4188c0c1b896', 67),
  ('8946b1ef-adef-4057-8f40-d5de803129e3', 68),
  ('d50c20fd-a4ab-443d-a6cf-d8b504003931', 69),
  ('5af03330-78bc-4e85-8e2f-1589825186f1', 70),
  ('2316a61f-016d-48ef-b9ce-460a07f8f11a', 71),
  ('938fc050-1961-4792-b6fc-b1cc7b275ff1', 72),
  ('e9b565c9-e14d-49c4-85da-7d0d95817f81', 73),
  ('59e73ded-b632-4954-bc34-4a0456d0fc8b', 74),
  ('c1fbcf38-9217-4d31-94e0-3a76aee3bfae', 75),
  ('7b071abd-3413-4269-a38e-b0165eb20495', 76),
  ('e60b92db-52ec-46f3-854c-a0e45ecea916', 77),
  ('acc51f6c-8e68-4777-a244-291329594295', 78),
  ('2dd2a145-5f88-42e3-84b8-db7d9a90629d', 79),
  ('deb595ce-c78f-438f-8146-5f516d5e22a9', 80),
  ('7e4d9e1e-f499-429a-a107-d35fd9d316a6', 81),
  ('e3072868-eea4-45f4-9ff4-dacdebb6a922', 83),
  ('ff8e0156-a3ca-45f3-8e15-95f979f909e9', 84),
  ('5efa75bf-6cac-4673-badc-0ad33cd745f4', 85),
  ('9f6444c9-5563-47e1-9ec1-f64d56add559', 86),
  ('3598b2a2-36d4-4bab-a5aa-a6b9d4d5d9d7', 87),
  ('44565461-4081-4708-911a-0bc815729e0d', 88),
  ('c90ac794-67e3-43cc-820a-90fe5c7b4f57', 89),
  ('e7d89f25-1b33-4f1d-be88-b100d2ee9062', 90),
  ('26e10ff1-9874-41a8-a505-4dea5ed3ca30', 91),
  ('1024c1c1-abc6-4b4b-824c-e1e908931141', 92),
  ('eda5dd8d-8093-4b32-b930-d87e589a4538', 93),
  ('218b4df0-5e1b-48a7-8b3c-c34cad4e27b0', 94),
  ('56722696-eb30-4435-b54a-a3fb1b8a38a5', 95),
  ('e285987d-3ced-4488-b0b4-250df95ab315', 96),
  ('2343d5a6-6f3d-4493-a390-ad441964e989', 97),
  ('5b007b65-40ec-4fa5-bfc4-c46bc9ad86bd', 98),
  ('d0788fd7-f1c2-49e4-afe1-53816a36f374', 99),
  ('fd0d3ad3-7553-4fc7-80ba-86695f9181d0', 100)
) as v(title_id, position)
cross join public.curated_lists cl
where cl.slug = 'afi-top-100'
on conflict do nothing;

insert into public.curated_list_titles (curated_list_id, title_id, position)
select cl.id, v.title_id::uuid, v.position
from (values
  ('f76eec56-2ec3-4ea3-84b3-3c4e743fd1f7', 1),
  ('b8bdc925-d273-47b2-9b1b-3140f2819bf2', 2),
  ('8d3c6ea3-f390-41e3-abad-548ce07f280d', 3),
  ('912cd58c-b8d7-4794-9794-1d40d361c346', 4),
  ('b25b9e3d-22e3-4331-b6b8-7d87896b4f10', 5),
  ('21ec3975-c694-46c7-87a9-29a6a8cb7b8d', 6),
  ('9f3cf9bc-544e-4b9b-9885-9c10fafeab7c', 7),
  ('2b7e26b4-0725-4092-b888-889d2e9fa5d1', 8),
  ('c00a08db-89fa-4660-92ed-7f7798e271da', 9),
  ('8d315626-9148-41a8-9029-e2e7c5568f9c', 10),
  ('255d4a77-4c40-496e-8b19-3eb5029f030e', 11),
  ('06706adb-67df-43fe-a8e3-648c2acb9583', 12),
  ('cc26f61b-9607-4076-a72b-b2cdbeac7817', 13),
  ('23fd9c24-96c9-4734-9a43-824404c7ac4b', 14),
  ('aef5dd18-eb02-4abf-8d28-27e49799eb8a', 15),
  ('546b0bec-488f-469b-8999-ec923170c3d4', 16),
  ('01f1685f-045d-4c36-8517-17cbb292895f', 17),
  ('1bbc5b85-fb0d-4ae7-b91c-a0fad008f490', 18),
  ('375cb5b7-9131-435d-9f1a-dfba99134013', 19),
  ('8ee8f051-8576-4d37-b583-a395ea16b76b', 20),
  ('9432da99-4584-4e85-b7e0-743882a64d62', 21),
  ('0727eb9b-1263-4050-ae3d-94343f4b0ec9', 22),
  ('a99ea291-047b-4e15-8963-99be15940810', 23),
  ('1108bd10-9528-4b47-974b-7900ce3f9018', 24),
  ('d0e32ce7-1c3c-46d8-af2f-270d5a10eed9', 25),
  ('d5fe8cfe-679f-4ed5-9397-dec0d8164f7b', 26),
  ('266d97e4-d364-43ef-8d1d-d20531833a37', 27),
  ('e28150ec-a955-4565-a955-c1881475af6b', 28),
  ('f9bd4417-9c2e-4d66-af91-23705d025d28', 29),
  ('9157e6d4-55b6-4f79-806a-3c883ec8b85d', 30),
  ('a00daf31-0e91-4ba6-a6a7-27f4a638cf29', 31),
  ('b14512a1-2689-4924-864b-c902d83de6f7', 32),
  ('69a5aa9e-30db-4b75-8fee-59f89be8deb5', 33),
  ('b26757b3-4d5c-4888-b69b-0050448899b4', 34),
  ('e93da2ac-7f8a-4128-b5a6-6671dfb7c02d', 35),
  ('5e7b2752-a4c0-4ff9-8d55-9d37b511828e', 36),
  ('8cf851d1-8eb4-482f-901c-b98bb9cb341d', 37),
  ('03877b3d-a191-4e31-83a0-9e5345fa5024', 38),
  ('232ac197-3238-4e9a-a201-3d8e7811d0bd', 39),
  ('aa64bbb5-cea0-498f-a608-11fb76db0cc3', 40),
  ('c9370691-df0a-48d5-9dfe-b1cb9bf3e2da', 41),
  ('a061e8db-1664-4d48-a7d3-c26fddf3a605', 42),
  ('22e9c803-e229-4a38-bfdc-04aa05becdac', 43),
  ('084f1655-0abc-4a04-9c13-51442b9ee426', 44),
  ('aff773d8-57d2-440c-bbe0-6109b52f4c07', 45),
  ('25848017-26b0-4889-9989-234547bf86db', 46),
  ('818272c4-d7dd-414e-ad39-66e69da7d9a5', 47),
  ('403a4cca-b004-40b4-abb2-c77f9e4a1009', 48),
  ('47ebc804-7575-4492-9b75-a921eb19bee9', 49),
  ('a697b60a-c0e4-4adb-90eb-c1742cebc988', 50)
) as v(title_id, position)
cross join public.curated_lists cl
where cl.slug = 'greatest-tv-shows'
on conflict do nothing;
